# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import linter_pb2 as linter__pb2


class LinterStub(object):
    """Interface exported by all linters.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.LintCode = channel.unary_unary(
                '/Linter/LintCode',
                request_serializer=linter__pb2.LintingRequest.SerializeToString,
                response_deserializer=linter__pb2.LintingResult.FromString,
                )


class LinterServicer(object):
    """Interface exported by all linters.
    """

    def LintCode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LinterServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'LintCode': grpc.unary_unary_rpc_method_handler(
                    servicer.LintCode,
                    request_deserializer=linter__pb2.LintingRequest.FromString,
                    response_serializer=linter__pb2.LintingResult.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Linter', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Linter(object):
    """Interface exported by all linters.
    """

    @staticmethod
    def LintCode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Linter/LintCode',
            linter__pb2.LintingRequest.SerializeToString,
            linter__pb2.LintingResult.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
