# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: linter.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x0clinter.proto\"\x1e\n\x0eLintingRequest\x12\x0c\n\x04\x63ode\x18\x01 \x01(\t\"0\n\rLintingResult\x12\x0e\n\x06status\x18\x01 \x01(\x05\x12\x0f\n\x07\x63omment\x18\x02 \x01(\t27\n\x06Linter\x12-\n\x08LintCode\x12\x0f.LintingRequest\x1a\x0e.LintingResult\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'linter_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
    DESCRIPTOR._options = None
    _globals['_LINTINGREQUEST']._serialized_start = 16
    _globals['_LINTINGREQUEST']._serialized_end = 46
    _globals['_LINTINGRESULT']._serialized_start = 48
    _globals['_LINTINGRESULT']._serialized_end = 96
    _globals['_LINTER']._serialized_start = 98
    _globals['_LINTER']._serialized_end = 153
# @@protoc_insertion_point(module_scope)
